config/routes.rb
Rails.application.routes.draw do
  root to: 'ideas#toppage'

  resources :ideas do
    member do
      post "follow"
      delete "unfollow"
      post "like"
      delete "dislike"
    end
    collection do
      get 'toppage'
    end
  end

  resources :users do
  end

  get '/login', to: "session#new"
  post '/login', to: 'session#create'
  delete '/logout', to: 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classification_of_idea.rb
class ClassificationOfIdea < ApplicationRecord
  has_many :ideas, foreign_key: :class_id
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :ideaname, presence: { message: "アイデア名を入力してください" }
  validates :description, presence: { message: "説明文を入力してください" }

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :classification_of_idea

  has_many :joinings
  has_many :users, through: :joinings, dependent: :destroy

  has_many :skill_ideas
  has_many :skills, through: :skill_ideas, dependent: :destroy

  has_many :likes
  has_many :users, through: :likes, dependent: :destroy

  has_one_attached :image, dependent: :destroy

  def self.ransackable_attributes(_auth_object = nil)
    %w[ideaname]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def liked_by?(user_id)
    likes.where(user_id: user_id).exists?
  end

  scope :limit_display, -> { limit(20).reverse_order }
end

app/models/joining.rb
class Joining < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :idea, optional: true

  validates :user_id, uniqueness: { scope: :idea_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :idea, optional: true

  validates :user_id, uniqueness: { scope: :idea_id }
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :skill_users
  has_many :users, through: :skill_users

  has_many :skill_ideas
  has_many :ideas, through: :skill_ideas
end

app/models/skill_idea.rb
class SkillIdea < ApplicationRecord
  belongs_to :idea
  belongs_to :skill
end

app/models/skill_user.rb
class SkillUser < ApplicationRecord
  belongs_to :skill
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: { message: "名前を入力してください" }
  validates :mail, presence: { message: "メールアドレスを入力してください" }, uniqueness: { message: "既に登録されているアドレスです" }
  validates :password, presence: { message: "パスワードを入力してください" }, length: { minimum: 10, message: "パスワードは１０文字以上で登録してください" }, on: :create

  has_many :ideas, foreign_key: :owner_id, dependent: :destroy

  has_many :joinings
  has_many :ideas, through: :joinings, dependent: :destroy

  has_many :skill_users
  has_many :skills, through: :skill_users, dependent: :destroy

  has_many :likes
  has_many :ideas, through: :likes, dependent: :destroy

  has_one_attached :avatar, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # 共通分部分である検索窓に関連して「＠ｑのインスタンスを生成していない」とエラー文が出たので追記
  def ransackable
    @q = Idea.ransack(params[:q])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :ransackable

  def index
    # limit_displayは最大表示に関するファンクション
    @ideas = @q.result(distinct: true).limit_display
    @user = User.find(current_user.id)
  end

  # 　新たに他ユーザのアイデアをフォローする場合
  def follow
    @followings = current_user.joinings.new(idea_id: params[:id])
    @idea = Idea.find(params[:id])
    @owner = User.find(@idea.owner_id)
    @follower = User.find(current_user.id)
    if @followings.save
      IdeaMailer.follower_email(@follower, @owner).deliver_now
      redirect_to root_url
    else
      flash[:notice] = "#{@owner.name}を二重にフォローできません"
      redirect_to idea_path(params[:id])
    end
  end

  def unfollow
    @joining = Joining.find_by(user_id: current_user.id, idea_id: params[:id])
    @joining.delete
  end

  def like
    @likes = current_user.likes.new(idea_id: params[:id])
    @idea = Idea.find(params[:id])
    respond_to :js if @likes.save
  end

  def dislike
    @like = Like.find_by(user_id: current_user.id, idea_id: params[:id])
    @idea = Idea.find(params[:id])
    respond_to :js if @like.destroy
  end

  # アイデアの詳細の表示
  def show
    @idea = Idea.find_by(id: params[:id])
    @user = User.find(@idea.owner_id)
    @skills = @idea.skills
    @classification_of_idea = @idea.classification_of_idea
  end

  # ログイン中ユーザが新規でアイデアを作成
  def new
    @skills = Skill.all
    @classification_of_ideas = ClassificationOfIdea.all
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to ideas_path
    else
      render :new
    end
  end

  # ABOUTUSの中身
  def toppage; end

  def edit
    @idea = Idea.find(params[:id])
    @skills = Skill.all
    @classification_of_ideas = ClassificationOfIdea.all
  end

  def update
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    redirect_to root_url
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to root_url
  end

  private

  def idea_params
    params.require(:idea).permit(:ideaname, :description, :owner_id, :image, :classification_of_idea_id, skill_ids: [])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :ransackable

  def new; end

  def create
    @user = User.find_by(mail: session_params[:mail])
    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to ideas_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:mail, :password)
  end
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
    @test = Test.find(1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ransackable
  #ログインしていない場合はトップページへとリダイレクト
  before_action except: [:new, :create] do
    redirect_without_login
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "新規ユーザが登録されました"
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      flash.now[:notice]
      render :new
    end
  end

  def show
    @my_ideas = Idea.where(owner_id: params[:id])
    @my_ideas.each do |myidea|
      @followers = myidea.users
    end
    @user = User.find(params[:id])
    @skills = @user.skills
  end

  # 自分が作成したアイデアの表示 MY IDEAS
  def show_idea
    @my_ideas = Idea.where(owner_id: params[:id])
  end

  def edit
    @user = User.find(current_user.id)
    @skills = Skill.all
  end

  def update
    @user = User.find(current_user.id)
    @user.update(user_params)
    if @user.registered == 1
      #登録後の初回のみ表示されるインストラクションでボタンを押した時のみ
      render template: "idea/index"
    else
      #通常のユーザアカウントの更新の場合
      redirect_to user_path(current_user.id)
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :mail, :password, :password_confirmation, :introduction, :avatar, :registered, skill_ids: [])
  end

  def redirect_without_login
    redirect_to root_url if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def html_title(title = "")
    if title.empty?
      "SEEDS"
    else
      "#{title} - SEEDS"
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/dislike.js.erb
$('#like-container-<%= @idea.id%>').html("<%= j(render 'ideas/index_shared/likes', idea: @idea) %>");
$('.far.fa-heart.<%= @idea.id%>').addClass('likesAnimation');

app/views/ideas/edit.html.erb
<% provide(:title, @idea.ideaname) %>
<section>
  <div class="contents-wrapper">
    <div class="contents-container">
      <%= form_with model: @idea, local: true do |f| %>
        <table>
          <th colspan="2" class="td-head"><h1>アイデア編集</h1></th>
          <tr>
            <td class="td-left"><%= f.label :image, 'アイデアイメージ' %></td>
            <td class="td-right td-image-container">
              <div class="image-container">
                <% if @idea.image.attached? %>
                  <%= image_tag @idea.image %>
                <% else %>
                  <img src="/assets/AdobeStock_210005036_Preview.jpeg">
                <% end %>
              </div>
            </td>
          </tr>
          <tr>
            <td class="td-left"><%= f.label :ideaname, "アイデア名" %></td>
            <td class="td-title"><%= f.text_field :ideaname,　value: @idea.ideaname, class: "idea-name input-box" %></td>
          </tr>
          <tr>
            <td class="td-left"><%= f.label :description, "詳細" %></td>
            <td> <%= f.text_area :description, value: @idea.description, class: "idea-description input-box" , size: "40*20" %></td>
          </tr>
          <tr>
            <td><% f.hidden_field :owner_id, value: current_user.id %></td>
          </tr>
          <tr>
            <td class="td-left">アイデア目的</td>
            <td>
              <div class="check-box">
                <%= f.collection_select(:classification_of_idea_id, @classification_of_ideas, :id, :idea_class)%>
              </div>
            </td>
          </tr>
          <tr>
            <td class="td-left"><%= f.label :skills, "募集スキル" %></td>
            <td class="td-right">
              <%= f.collection_check_boxes(:skill_ids, @skills, :id, :skillname, include_hidden: false, checked: @idea.skill_ids) do |b| %>
                <div class="check-box">
                <%= b.label { b.check_box + b.text } %>
                </div>
              <% end %>
            </td>
          </tr>
          <tr>
            <td colspan="2" class="td-left"><%= f.file_field :image %></td>
          </tr>
          <tr>
            <td colspan="2" class="td-left"><%= f.submit "更　新", class:"btn-box" %></td>
          </tr>
          <tr>
            <td colspan="2" class="td-left"><%= link_to "アイデア削除", idea_path(@idea.id), method: :delete, data: { confirm: 'マイアイデアを削除しますか？'}, class:"btn-box" %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</section>

app/views/ideas/index.html.erb
<section id="idea-index">
  <div id="wrap">
    <% if @user.registered.nil? %>
      <div id="instruction-modal">
        <div id="instruction-of-picture">
          <p class="arrow-down"></p>
          <p>一番大きく表示されている絵は<b><big>最新</big></b>のアイデアです。</p>
        </div>
        <div id="instruction-classification">
          <p class="arrow-left"></p><p>アイデアの種類を示しています。</p>
        </div>
        <div id="classification-spot">
        </div>
        <div id="instruction-search-box">
          <p class="arrow-up"></p><p>検索はキーワードをホームページ上部の<b><big>検索ボックス</big></b>から検索できます。</p>
        </div>
        <div id="search-spot">
        </div>
        <div id="instruction-box">
          <h1>お気に入りの種を見つけよう</h1>
          <p>まずは、どのような<b><big>アイデア</big></b>があるか見てみましょう。</p>
          <div class="close-button-container">
            <%= form_with model: @user do |f| %>
              <%= f.hidden_field :registered, value: 1 %>
              <%= f.submit "早速始める", id:"close-button" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <% if @ideas.present? %>
      <% @ideas.each_with_index do |idea, i| %>
        <div class="item_container <%= i %>">
          <%= link_to idea_path(idea.id) do %>
          <h3 class="idea-class <%= idea.classification_of_idea_id%>">　<%= idea.ideaname %></h3>
          <div class="index-images">
            <% if idea.image.attached? %>
              <%= image_tag idea.image %>
            <% else %>
              <img src="/assets/AdobeStock_210644461_Preview.jpeg">
            <% end %>
          </div>
          <% end %>
          <div class="idea-description-modal">
            <%= link_to idea_path(idea.id) do %>
              <p class="idea-description"><%= idea.description%></p>
            <% end%>
          </div>
          <!--ログイン中ユーザによって既にいいねされていればtruth-->
          <% if current_user.present? %>
            <% if not current_user.id == idea.owner_id %>
              <div id="like-container-<%= idea.id %>">
                <%= render "ideas/index_shared/likes", idea: idea %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="no-result">
        <h1>該当するアイデアは見つかりませんでした</h1>
      </div>
    <% end %>
  </div>
</section>

app/views/ideas/index_shared/_likes.erb
  <% if idea.liked_by?(current_user.id) %>
  <!-- すでに「いいね」を押している場合 -->
    <%= link_to dislike_idea_path(idea.id), method: :delete, remote: true, class: "dislike" do %>
      <i class="fas fa-heart <%= idea.id %>"><span><%= idea.likes.count %>いいね</span></i>
    <% end %>
  <% else %>
  <!-- まだ「いいね」を押していない場合 -->
    <%= link_to like_idea_path(idea.id), method: :post, remote: true, class: "like" do %>
      <i class="far fa-heart <%= idea.id %>"><span><%= idea.likes.count %>いいね</span></i>
    <% end %>
  <% end %>
  <!-- farは空白のハート、fasはその逆 -->

app/views/ideas/like.js.erb
$('#like-container-<%= @idea.id%>').html("<%= j(render 'ideas/index_shared/likes', idea: @idea) %>");
$('.fas.fa-heart.<%= @idea.id%>').addClass('likesAnimation');

app/views/ideas/show.html.erb
<% provide(:title, @idea.ideaname) %>
<section id="idea-show">
  <div class="contents-wrapper">
    <div class="contents-container">
      <table>
        <tr>
          <th colspan="2"><h1>アイデア詳細</h1></th>
        </tr>
        <tr>
          <th colspan="2"><h1>アイデア提案者</h1></th>
        </tr>
        <tr>
          <th colspan="2" class="show-name-link"><h1><%= link_to "#{@user.name}", user_path(@user.id) %></h1></th>
        </tr>
        <tr>
          <td class="td-left">アイデアイメージ</td>
          <td  class="td-image-container">
            <div class="image-container">
              <% if @idea.image.attached? %>
                <%= image_tag @idea.image %>
                <% else %>
                <img src="/assets/AdobeStock_210005036_Preview.jpeg">
              <% end %>
            </div>
          </td>
        </tr>
        <tr>
          <td class="td-left"><p>アイデア名</p></td>
          <td class="td-right"><%= @idea.ideaname %></td>
        </tr>
        <tr>
          <% if @classification_of_idea.present? %>
            <td class="td-left"><p>募集目的</p></td>
            <td class="td-title"><%= @classification_of_idea.idea_class %></td>
          <% end %>
        </tr>

        <tr>
          <td class="td-left">アイデア紹介</td>
          <td class="td-right"><%= @idea.description %></td>
        </tr>
        <tr>
          <td class="td-left">募集スキル</td>
          <td class="td-right">
            <% @skills.each do |skill| %>
              <div class="check-box">
                <%= skill.skillname %>
              </div>
            <% end %>
          </td>
        </tr>
        <% if not current_user.id == @idea.owner_id %>
          <tr>
            <td colspan="2">
              <div class="td-left">
                <%= link_to "フォローする", follow_idea_path, method: :post, class:"btn-box" %>
              </div>
            </td>
          </tr>
        <% else %>
          <tr>
            <td colspan="2">
              <div class="td-left">
                <%= link_to "編集する", edit_idea_path(@idea.id), class:"btn-box" %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
</section>

app/views/ideas/toppage.html.erb
<% provide(:title, "トップページ") %>
<section id="idea-toppage">

  <div class="main-contents-wrapper">
    <div id="theme-container" class="scroll-animation">
     <h1 class="main-title">-SEEDS- </h1>
     <h2 class="main-copy ">アイデアの種を撒き、仲間と共に、大きく育てよう</h2>
     <div class="top-main-image-container">
       <img src="/assets/joshua-lanzarini-Vct0oBHNmv4-unsplash.jpg" alt="seeds">
     </div>
    </div>

    <div id="feature-contaienr" class="scroll-animation">
      <div class="top-feature-descrption-contaienr">
        <h1>自分の中に眠っている種を撒こう</h1>
          <p>世の中に出回る良いアイデアはほんの一握りです。</p>
          <p><b><big>"普通の人"</big></b>であっても芽吹けば大きく育つ可能性のある種（アイデア）をもっているハズ</p>
          <p>でも種を蒔かなければ芽はでません</p>
          <p>その種も一人で芽吹き、育つのは難しいでしょう</p>
          <p>豊かな<b><big>土、水、太陽</big></b>が揃って大きく育つのです。</p>
          <p>そんな、まだ芽吹いていない種が芽吹く<b><big>土壌</big></b>がここにあります</p>
          <p>多くの人とアイデアを共有して立派な木を育てましょう！</p>
      </div>
      <div class="top-feature-image-container fromleft">
        <img src="/assets/gabriel-jimenez-jin4W1HqgL4-unsplash.jpg" alt="soil">
      </div>
    </div>

     <div id="how-to-start" class="scroll-animation">
       <div class="first-step-conatainer" >
         <h1>お気に入りの種を見つけよう</h1>
         <p>まずは、どのような<b><big>アイデア</big></b>があるのか見てみましょう。</p>
         <p>キーワード検索で気になるキーワードを入れて調べてみましょう</p>
         <p>きっとお気に入りが見つかるハズです。</p>
       </div>
       <div class="how-to-start-image-container">
         <img src="/assets/maddi-bazzocco-UhrHTmVBzzE-unsplash.jpg" alt="">
       </div>
     </div>

     <div id="how-to-launch" class="scroll-animation">
       <div class="how-to-launch-image-container">
         <img src="/assets/jessica-delp-__VuwL8Tano-unsplash.jpg" alt="watering">
       </div>
       <div class="second-step-conatainer scroll-animation">
         <h1>自分の種を播こう</h1>
         <p>自分のオリジナルのアイデアを投稿することができます。</p>
         <p>イメージ写真もつけることができるので、魅力的なイメージ写真をつけましょう</p>
         <p>アイデアを具現化するのに、何が必要か明示すると仲間も見つかり易くなります</p>
       </div>
     </div>

     <div id="how-to-realize" class="scroll-animation">
       <div class="how-to-realize-image-container">
         <img src="/assets/markus-winkler-ypOsSfRgKZ4-unsplash.jpg" alt="watering">
       </div>
       <div class="third-step-container scroll-animation">
         <h1>育てよう</h1>
         <p>気に入ったアイデアはフォローすることができます。</p>
         <p>フォローするとアイデアの主に自動的にフォローしたことを知らせることができます。</p>
         <p>自分のアイデアのフォロワーとも連絡をとってみましょう。</p>
       </div>
     </div>
    </div>
</section>

<% if not current_user %>
  <div class="login-modal-wrapper">
    <div id="sign-up-container-modal">
      <h1>さあ種を播こう！</h1>
      <div class="top-link-container">
        <div class="link-container">
          <ul>
            <%= link_to new_user_path do%>
              <li class="top-sign-up">SIGN UP</li>
              <li><p>アカウントをお持ちでない方はこちらから</p></li>
            <% end %>
          </ul>
        </div>
        <div class="link-container">
          <ul>
            <%= link_to login_path do %>
              <li class="top-login">LOG IN</li>
              <li><p>アカウントをお持ちの方はこちらから</p></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2020-<%= Time.current.year %> Copyright SEED .</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<header>
  <div class="nav-bar">
    <div class="container">
      <div class="header-logo">
        <img src="/assets/pinterest_profile_image.png" alt="main logo">
      </div>
      <div class="header-search">
        <% if current_user %>
          <ul>
            <%= search_form_for @q, id: "search_form", class: "search-container" do |f| %>
            <li><% f.label :ideaname_cont %></li>
            <li><%= f.search_field :ideaname_cont, value:"", class:"search-window" %><%= f.submit "SEARCH", class: "search-btn" %><i class="fas fa-search"></i></li>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="header-users">
        <div class="header-users-hamburger">
          <ul>
            <li class="list"><%= link_to "ABOUT US", toppage_ideas_path, class:"header-list" %></li>
<!--アイデア一覧画面は、masonry-railsのgemをもって表示しているが、turbolinksの影響で遷移した際に正常に表示されない為,turbolinksをfalseにしている。-->
         <% if current_user %>
            <li class="list"><%= link_to "LAUNCH YOUR IDEA!", new_idea_path, class:"header-list" %></li>
            <li class="list"><%= link_to "IDEAS", ideas_path,data: {"turbolinks"=>false}, class:"header-list" %></li>
            <li class="list"><%= link_to "MY ACCOUNT", user_path(current_user.id) %></li>
            <li class="list"><%= link_to "LOGOUT", logout_path, method: :delete, class:"header-list" %></li>
          <% else %>
            <li><%= link_to "LOGIN", login_path, class:"header-list" %></li>
            <li><%= link_to "SIGN UP", new_user_path, class:"header-list" %></li>
          <% end %>
          </ul>
        </div>
      </div>
      <div id="open-nav" class="">
        <i class="fas fa-bars"></i>
      </div>
    </div>
    <div class="menu-container">
      <ul>
        <li id="close-nav">
            <i class="fas fa-times"></i>
        </li>
        <li class="list"><%= link_to "ABOUT US", toppage_ideas_path, class:"header-list" %></li>
        <% if current_user %>
          <li class="list"><%= link_to "LAUNCH YOUR IDEA!", new_idea_path, class:"header-list" %></li>
          <li class="list"><%= link_to "IDEAS", ideas_path,data: {"turbolinks"=>false}, class:"header-list" %></li>
          <li class="list"><%= link_to "MY ACCOUNT", user_path(current_user.id) %></li>
          <li class="list"><%= link_to "LOGOUT", logout_path, method: :delete, class:"header-list" %></li>
        <% else %>
          <li><%= link_to "IDEAS", ideas_path,data: {"turbolinks"=>false}, class:"header-list" %></li>
          <li><%= link_to "LOGIN", login_path, class:"header-list" %></li>
          <li><%= link_to "SIGN UP", new_user_path, class:"header-list" %></li>
        <% end %>
      </ul>
    </div>
  </div>


  <div class="flash-message-container">
    <% if flash[:notice] %>
      <div class="flash-notice">
        <%= flash[:notice] %>
      </div>
      <% end %>
  </div>
</header>

app/views/shared/header_shared/_menu_container.html.erb
<div class="menu-container">
  <ul>
    <li class="list"><%= link_to "ABOUT US", toppage_ideas_path, class:"header-list" %></li>
    <% if current_user %>
    <li class="list"><%= link_to "LAUNCH YOUR IDEA!", new_idea_path, class:"header-list" %></li>
    <li class="list"><%= link_to "IDEAS", ideas_path,data: {"turbolinks"=>false}, class:"header-list" %></li>
    <li class="list"><%= link_to "MY ACCOUNT", user_path(current_user.id) %></li>
    <li class="list"><%= link_to "LOGOUT", logout_path, method: :delete, class:"header-list" %></li>
    <% else %>
    <li><%= link_to "IDEAS", ideas_path,data: {"turbolinks"=>false}, class:"header-list" %></li>
    <li><%= link_to "LOGIN", login_path, class:"header-list" %></li>
    <li><%= link_to "SIGN UP", new_user_path, class:"header-list" %></li>
    <li><a href="#"><img src="" alt="account symbol"></a></li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<% provide(:title, current_user.name) %>
<section id="user-show">
  <div class="user-show-contents-container">
    <table>
      <% if @user.id == current_user.id %>
        <tr>
          <th colspan="4"><h1>マイ　アカウント</h1></th>
        </tr>
      <% else %>
        <tr>
          <th colspan="4"><h1><%= @user.name %>のアカウント</h1></th>
        </tr>
      <% end %>
      <tr>
        <td colspan="4">
          <div class="td-image-container">
            <div class="image-container-avatar">
              <% if @user.avatar.attached? %>
                <%= image_tag @user.avatar %>
              <% else %>
                <img src="/assets/AdobeStock_210005036_Preview.jpeg">
              <% end %>
            </div>
          </div>
        </td>
      </tr>
      <tr>
        <td colspan="2"><p>アカウント名</p></td>
        <td colspan="2"><%= @user.name %></td>
      </tr>
      <tr>
        <td colspan="2"><p>自己紹介</p></td>
        <td colspan="2"><%= @user.introduction %></td>
      </tr>
      <tr>
        <td colspan="2"><p>ユーザアドレス</p></td>
        <td colspan="2"><%= @user.mail %></td>
      </tr>
      <tr>
        <td colspan="4" class="td-left"><h1>ユーザーのアイデア</h1></td>
      </tr>
       <%= render "users/show_shared/show_myideas", my_ideas: @my_ideas, followers: @followers %>
       <%= render "users/show_shared/show_followings", followings: @followings, user: @user %>
       <%= render "users/show_shared/show_skills", skills: @skills %>
      <% if @user.id == current_user.id %>
        <tr>
          <td colspan="2"><%= link_to "アカウント編集", edit_user_path(current_user.id) , class:"btn-box"%></td>
          <td colspan="2"><%= link_to "アカウント削除", user_path(current_user.id), method: :delete, data: { confirm: 'アカウントを削除しますか？'}, class:"btn-box" %></td>
        </tr>
      <% end %>

    </table>
  </div>
</section>

app/views/users/show_shared/_show_followings.erb
<tr>
  <td colspan="4" class="td-left"><h1>フォローしているアイデア</h1></td>
</tr>
<% current_user.joinings.each do |joining| %>
  <tr>
    <td class="user-show-first-column">
      <%= link_to idea_path(joining.idea.id) do %>
        <%= joining.idea.ideaname %>
      <% end %>
    </td>
    <td class="user-show-second-column">
      <div class="user-show-image-container">
        <%= link_to idea_path(joining.idea.id) do %>
          <% if joining.idea.image.attached? %>
            <%= image_tag joining.idea.image %>
          <% else %>
            <img src="/assets/AdobeStock_210005036_Preview.jpeg">
          <% end %>
        <% end %>
      </div>
    </td>
    <% if user.id == current_user.id %>
      <td class="user-show-third-column"><%= joining.idea.description %></td>
      <td class="user-show-fourth-column"><%= link_to "フォローを外す", unfollow_idea_path(joining.idea.id), method: :delete, remote: true, class: "follow-delete-btn" %></td>
    <% else %>
      <td colspan="2" class="user-show-third-column"><%= joining.idea.description %></td>
    <% end %>
  </tr>
<% end %>